import os
import random
import re
from typing import List, Dict, Any
from pydantic import BaseModel
from .google_adk import Agent, SessionState
from ..utils.security import sanitize_input_text

from pydantic import Field

# Define Pydantic schema for structured Gemini generation
class QuizQuestion(BaseModel):
    question: str
    options: List[str] = Field(default_factory=list)
    correct: str
    explanation: str
    type: str = Field(default="mcq")

class QuizSchema(BaseModel):
    questions: List[QuizQuestion]

class QuizAgent(Agent):
    """
    Quiz Agent: Generates practice quizzes and evaluates results.
    Integrates with Google Gemini API when available, and falls back to a 
    highly customized, level-aware offline quiz generator.
    """
    def __init__(self):
        super().__init__(
            name="QuizAgent",
            instruction="You generate interactive multiple-choice quizzes on specific topics or uploaded study notes."
        )
        
        # Pre-built question bank for popular topics organized by topic and level
        self.question_bank = {
            "python": {
                "Beginner": [
                    {
                        "question": "What is the correct syntax to output 'Hello World' in Python?",
                        "options": ["print('Hello World')", "echo('Hello World')", "Console.WriteLine('Hello World')", "printf('Hello World')"],
                        "correct": 0,
                        "explanation": "In Python, the print() function is used to output text to the console."
                    },
                    {
                        "question": "How do you start a comment in Python?",
                        "options": ["// this is a comment", "/* this is a comment */", "# this is a comment", "<!-- this is a comment -->"],
                        "correct": 2,
                        "explanation": "Python uses the hash (#) character to start single-line comments."
                    },
                    {
                        "question": "What keyword is used to define a function in Python?",
                        "options": ["func", "def", "function", "define"],
                        "correct": 1,
                        "explanation": "The 'def' keyword is used to declare a function in Python."
                    },
                    {
                        "question": "Which of the following data types is immutable in Python?",
                        "options": ["list", "dictionary", "set", "tuple"],
                        "correct": 3,
                        "explanation": "Tuples are immutable sequences, whereas lists, dictionaries, and sets are mutable."
                    },
                    {
                        "question": "What is the value of 3 * 1 ** 3 in Python?",
                        "options": ["27", "9", "3", "1"],
                        "correct": 2,
                        "explanation": "Exponentiation (**) has higher precedence than multiplication (*). So 1 ** 3 = 1, and 3 * 1 = 3."
                    }
                ],
                "Intermediate": [
                    {
                        "question": "What is the difference between a list and a tuple in Python?",
                        "options": ["Lists are immutable, tuples are mutable", "Lists are mutable, tuples are immutable", "Lists are ordered, tuples are unordered", "Lists can contain duplicates, tuples cannot"],
                        "correct": 1,
                        "explanation": "Lists in Python are mutable, meaning their elements can be changed, added, or removed. Tuples are immutable and cannot be modified after creation."
                    },
                    {
                        "question": "What is the output of the expression: [x for x in range(5) if x % 2 == 0]?",
                        "options": ["[1, 3]", "[0, 2, 4]", "[0, 1, 2, 3, 4]", "[2, 4]"],
                        "correct": 1,
                        "explanation": "This list comprehension filters numbers from 0 to 4 (generated by range(5)), returning only even numbers."
                    },
                    {
                        "question": "How can you catch multiple specific exceptions in a single try-except block?",
                        "options": ["except (ValueError, TypeError):", "except ValueError, TypeError:", "except ValueError or TypeError:", "except [ValueError, TypeError]:"],
                        "correct": 0,
                        "explanation": "In Python, multiple exceptions are caught by passing them as a parenthesized tuple in the except clause."
                    },
                    {
                        "question": "Which of the following functions generates a sequence of numbers in Python?",
                        "options": ["loop()", "sequence()", "range()", "generate()"],
                        "correct": 2,
                        "explanation": "The range() function returns a sequence of numbers, starting from 0 by default, and increments by 1, and stops before a specified number."
                    },
                    {
                        "question": "What does the *args parameter do in a function definition?",
                        "options": ["It accepts positional arguments as a tuple", "It accepts keyword arguments as a dictionary", "It multiplies the input arguments", "It marks a variable as global"],
                        "correct": 0,
                        "explanation": "*args allows a function to accept any number of positional arguments as a tuple."
                    }
                ],
                "Advanced": [
                    {
                        "question": "What is the Method Resolution Order (MRO) in Python multiple inheritance?",
                        "options": ["Depth-first, then right-to-left", "C3 Linearization algorithm", "Breadth-first search", "Left-to-right lookup order"],
                        "correct": 1,
                        "explanation": "Python uses the C3 Linearization algorithm to determine the Method Resolution Order (MRO) in multiple inheritance hierarchies."
                    },
                    {
                        "question": "What is the purpose of the '__slots__' attribute in a Python class?",
                        "options": ["To define class constructor hooks", "To optimize memory by preventing dynamic __dict__ creation", "To declare abstract methods", "To handle thread-safe attributes"],
                        "correct": 1,
                        "explanation": "Declaring '__slots__' reserves space for a fixed set of attributes, avoiding the memory overhead of a dictionary for each instance."
                    },
                    {
                        "question": "How does a custom context manager handle exceptions raised within its block using __exit__?",
                        "options": ["By raising a StopIteration exception", "By returning True to suppress the exception", "By calling sys.exit()", "By returning False to suppress the exception"],
                        "correct": 1,
                        "explanation": "If the __exit__ method of a context manager returns True, the exception raised in the with block is suppressed. If it returns False or None, the exception propagates."
                    },
                    {
                        "question": "What is the difference between a shallow copy and a deep copy of a list?",
                        "options": ["Shallow copies reference nested objects; deep copies duplicate nested objects", "Deep copies are faster than shallow copies", "Shallow copies use the copy module; deep copies use duplicate module", "There is no difference in Python"],
                        "correct": 0,
                        "explanation": "A shallow copy constructs a new compound object and inserts references to the objects found in the original. A deep copy recursively inserts copies of the objects found in the original."
                    },
                    {
                        "question": "What does a metaclass do in Python?",
                        "options": ["It is a class that inherits from multiple parent classes", "It defines the behavior and creation rules for class objects", "It is a class used for meta-programming APIs", "It is an abstract class contract"],
                        "correct": 1,
                        "explanation": "A metaclass is a class of a class. It defines how a class is constructed (typically by inheriting from 'type')."
                    }
                ]
            },
            "webdev": {
                "Beginner": [
                    {
                        "question": "What does HTML stand for?",
                        "options": [
                            "Hyper Text Markup Language",
                            "Home Tool Markup Language",
                            "Hyperlinks and Text Markup Language",
                            "Hyperlink Text Management Language"
                        ],
                        "correct": 0,
                        "explanation": "HTML stands for Hyper Text Markup Language. It is the standard markup language for creating web pages."
                    },
                    {
                        "question": "Which CSS property is used to change the text color of an element?",
                        "options": ["text-color", "fgcolor", "color", "font-color"],
                        "correct": 2,
                        "explanation": "The 'color' property in CSS is used to specify the text color of an element."
                    },
                    {
                        "question": "Which HTML tag is used to define an internal style sheet?",
                        "options": ["<css>", "<script>", "<style>", "<stylesheet>"],
                        "correct": 2,
                        "explanation": "The <style> tag is used to define internal CSS styling in an HTML document."
                    }
                ],
                "Intermediate": [
                    {
                        "question": "What is the purpose of JavaScript in web development?",
                        "options": [
                            "To structure web pages",
                            "To add style and layouts",
                            "To make web pages interactive and dynamic",
                            "To manage web server databases"
                        ],
                        "correct": 2,
                        "explanation": "JavaScript is a scripting language used to create dynamic, interactive content and handle client-side behavior on websites."
                    },
                    {
                        "question": "What is the CSS Box Model component that represents space outside the border?",
                        "options": ["padding", "margin", "content", "outline"],
                        "correct": 1,
                        "explanation": "In CSS, the margin is the space around elements outside of any defined borders."
                    },
                    {
                        "question": "Which HTTP method is most appropriate for submitting a form that updates server state?",
                        "options": ["GET", "POST", "HEAD", "OPTIONS"],
                        "correct": 1,
                        "explanation": "POST is used to send data to a server to create or update a resource."
                    }
                ],
                "Advanced": [
                    {
                        "question": "What is Cross-Site Scripting (XSS)?",
                        "options": [
                            "Injecting malicious SQL commands to access the database",
                            "Injecting malicious scripts into trusted websites that are executed by other clients",
                            "Intercepting network packets between client and server",
                            "Flooding a server with traffic to cause a denial of service"
                        ],
                        "correct": 1,
                        "explanation": "XSS occurs when malicious client-side scripts are injected into web applications and executed by the browser of an unsuspecting user."
                    },
                    {
                        "question": "What is the event loop in JavaScript/Node.js?",
                        "options": [
                            "A loop that executes all synchronous code blocks concurrently",
                            "A mechanism that schedules and runs asynchronous tasks on a single thread",
                            "A hardware component that handles network packets",
                            "An infinite loop that blocks browser rendering"
                        ],
                        "correct": 1,
                        "explanation": "The event loop allows JavaScript to perform non-blocking I/O operations by offloading tasks to the system kernel when possible."
                    },
                    {
                        "question": "What does CORS stand for, and why is it enforced by browsers?",
                        "options": [
                            "Core Object Resource Sharing; to speed up page loads",
                            "Cross-Origin Resource Sharing; to prevent malicious pages from reading data from another origin",
                            "Custom Origin Resource Security; to block all API requests",
                            "Client Object Request System; to validate user tokens"
                        ],
                        "correct": 1,
                        "explanation": "CORS stands for Cross-Origin Resource Sharing. It is a security mechanism enforced by browsers to control access to resources located outside a page's domain."
                    }
                ]
            },
            "datascience": {
                "Beginner": [
                    {
                        "question": "What is Supervised Learning in Machine Learning?",
                        "options": [
                            "Training a model on unlabeled data",
                            "Training a model on labeled training data (with input-output pairs)",
                            "Training a model through trial and error rewards",
                            "Manual inspection of model files by an engineer"
                        ],
                        "correct": 1,
                        "explanation": "Supervised Learning involves training a model on a labeled dataset, where each training example is paired with its correct output label."
                    },
                    {
                        "question": "In Python, which library is most commonly used for data manipulation and analysis?",
                        "options": ["NumPy", "Pandas", "Matplotlib", "Requests"],
                        "correct": 1,
                        "explanation": "Pandas is the leading Python library for data structures (DataFrames) and analysis, built on top of NumPy."
                    }
                ],
                "Intermediate": [
                    {
                        "question": "What does 'Overfitting' mean in Machine Learning?",
                        "options": [
                            "The model performs poorly on both training and test data",
                            "The model performs well on training data but poorly on unseen test data",
                            "The model runs too slowly on local servers",
                            "The model dataset has too few rows"
                        ],
                        "correct": 1,
                        "explanation": "Overfitting occurs when a model learns the detail and noise in the training data to an extent that it negatively impacts the performance of the model on new data."
                    },
                    {
                        "question": "What is the purpose of a validation set in machine learning?",
                        "options": [
                            "To train the model parameters",
                            "To tune hyperparameters and evaluate models during development",
                            "To serve as the final test set for deployment",
                            "To speed up the training computation time"
                        ],
                        "correct": 1,
                        "explanation": "The validation set is used to tune hyperparameters and select the best model configuration, preventing overfitting on the training set."
                    }
                ],
                "Advanced": [
                    {
                        "question": "What does 'Regularization' (L1/L2) accomplish in machine learning models?",
                        "options": [
                            "It speeds up model training iteration time",
                            "It prevents overfitting by adding a penalty term to the loss function to constrain weights",
                            "It guarantees the model is perfectly accurate",
                            "It imputes missing values in data frames automatically"
                        ],
                        "correct": 1,
                        "explanation": "L1 (Lasso) and L2 (Ridge) regularization add penalty costs to the model's loss function based on weight magnitudes to prevent overfitting."
                    },
                    {
                        "question": "What is the vanishing gradient problem in Deep Learning?",
                        "options": [
                            "Gradients become too large, causing weights to overflow",
                            "Gradients shrink exponentially as they propagate backward, causing early layers to learn very slowly",
                            "The optimizer runs out of memory on the GPU",
                            "Loss values decrease to zero instantly"
                        ],
                        "correct": 1,
                        "explanation": "In deep networks, backpropagating gradients can shrink exponentially toward zero, preventing early layers from updating weights effectively."
                    }
                ]
            }
        }

    def generate_quiz(self, topic: str, num_questions: int = 5, notes_content: str = None) -> List[Dict[str, Any]]:
        """
        Generates a quiz on a topic. If notes_content is provided, it extracts 
        questions dynamically. Uses Gemini when API key is active.
        """
        topic = sanitize_input_text(topic).lower()
        num_questions = max(1, min(10, num_questions))
        
        # Load user profile level
        from ..utils.db import get_user_profile
        try:
            profile = get_user_profile()
            skill_level = profile.get("level", "Beginner")
        except Exception:
            skill_level = "Beginner"
            
        if skill_level not in ["Beginner", "Intermediate", "Advanced"]:
            skill_level = "Beginner"
            
        # Check if Gemini API key is available
        api_key = os.environ.get("GEMINI_API_KEY")
        if api_key:
            try:
                from google import genai
                from google.genai import types
                client = genai.Client(api_key=api_key)
                
                if notes_content and len(notes_content.strip()) > 50:
                    prompt = (
                        f"Generate a {num_questions}-question practice quiz based on the following study notes.\n\n"
                        f"Target Skill Level: {skill_level}\n\n"
                        f"Study Notes:\n{notes_content}\n\n"
                        f"Requirements:\n"
                        f"1. Generate exactly {num_questions} questions.\n"
                        f"2. Mix question types: include Multiple-Choice (type='mcq'), Short-Answer (type='short_answer'), and Coding (type='coding') questions.\n"
                        f"3. For MCQ questions, 'options' must have exactly 4 choices, and 'correct' must be the index of the correct option as a string ('0', '1', '2', or '3').\n"
                        f"4. For Short-Answer questions, 'options' must be empty, and 'correct' must be the exact answer term or short phrase.\n"
                        f"5. For Coding questions, 'options' must be empty, and 'correct' must be the correct programming code snippet solution.\n"
                        f"6. Provide a clear, educational explanation for the correct answer.\n"
                        f"7. Match the targeted skill level ({skill_level}) in difficulty.\n"
                        f"8. Respond ONLY with valid JSON matching the requested schema."
                    )
                else:
                    prompt = (
                        f"Generate a {num_questions}-question practice quiz on the topic: '{topic}'.\n\n"
                        f"Target Skill Level: {skill_level}\n\n"
                        f"Requirements:\n"
                        f"1. Generate exactly {num_questions} questions.\n"
                        f"2. Mix question types: include Multiple-Choice (type='mcq'), Short-Answer (type='short_answer'), and Coding (type='coding') questions.\n"
                        f"3. For MCQ questions, 'options' must have exactly 4 choices, and 'correct' must be the index of the correct option as a string ('0', '1', '2', or '3').\n"
                        f"4. For Short-Answer questions, 'options' must be empty, and 'correct' must be the exact answer term or short phrase.\n"
                        f"5. For Coding questions, 'options' must be empty, and 'correct' must be the correct programming code snippet solution.\n"
                        f"6. Provide a clear, educational explanation for the correct answer.\n"
                        f"7. Match the targeted skill level ({skill_level}) in difficulty.\n"
                        f"8. Respond ONLY with valid JSON matching the requested schema."
                    )
                
                response = client.models.generate_content(
                    model="gemini-2.5-flash",
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        response_mime_type="application/json",
                        response_schema=QuizSchema,
                    ),
                )
                
                if response and response.text:
                    import json
                    data = json.loads(response.text)
                    questions = data.get("questions", [])
                    valid_questions = []
                    for q in questions:
                        if isinstance(q, dict) and "question" in q and "correct" in q and "explanation" in q:
                            q_type = q.get("type", "mcq")
                            correct_val = str(q["correct"]).strip()
                            if q_type == "mcq":
                                options_list = q.get("options", [])
                                if len(options_list) == 4 and correct_val.isdigit() and 0 <= int(correct_val) <= 3:
                                    q["correct"] = correct_val
                                    q["type"] = "mcq"
                                    valid_questions.append(q)
                            elif q_type in ["short_answer", "coding"]:
                                q["options"] = []
                                q["correct"] = correct_val
                                q["type"] = q_type
                                valid_questions.append(q)
                    if valid_questions:
                        return valid_questions[:num_questions]
            except Exception as e:
                print(f"Gemini API Quiz Exception: {str(e)}. Falling back to offline generator.")

        # Scenario 1: Generate from uploaded notes (offline rule-based)
        if notes_content and len(notes_content.strip()) > 50:
            return self._generate_from_notes(notes_content, num_questions)
            
        # Scenario 2: Pull from pre-built question bank (offline fallback)
        for key in self.question_bank:
            if key in topic or topic in key:
                # Retrieve questions for the specific level, fallback to Beginner if not present
                level_map = self.question_bank[key]
                questions = level_map.get(skill_level, level_map["Beginner"])
                
                shuffled = list(questions)
                random.shuffle(shuffled)
                
                selected_q = shuffled[:num_questions]
                formatted_q = []
                for q in selected_q:
                    fq = dict(q)
                    if "type" not in fq:
                        fq["type"] = "mcq"
                    fq["correct"] = str(fq["correct"])
                    formatted_q.append(fq)
                return formatted_q
                
        # Scenario 3: Generic quiz generator (fallback when topic doesn't match pre-built keys)
        return self._generate_generic_quiz(topic, num_questions, skill_level)

    def _generate_from_notes(self, text: str, num_questions: int) -> List[Dict[str, Any]]:
        """
        Rule-based question generation from notes text.
        Extracts key sentences and creates multiple-choice options.
        """
        sentences = re.split(r'(?<=[.!?])\s+', text)
        questions = []
        
        patterns = [
            (r"\b([A-Z][a-zA-Z\s]+)\b\s+is\s+defined\s+as\s+([^.]+)", "What is defined as: {}?"),
            (r"\b([A-Z][a-zA-Z\s]+)\b\s+refers\s+to\s+([^.]+)", "What does {} refer to?"),
            (r"\b([A-Z][a-zA-Z\s]+)\b\s+is\s+a\s+type\s+of\s+([^.]+)", "What type of concept is {}?"),
            (r"\b([A-Z][a-zA-Z\s]+)\b\s+consists\s+of\s+([^.]+)", "What does {} consist of?")
        ]
        
        parsed_facts = []
        for sentence in sentences:
            for pattern, question_template in patterns:
                match = re.search(pattern, sentence, re.IGNORECASE)
                if match:
                    term = match.group(1).strip()
                    definition = match.group(2).strip()
                    if len(term) > 2 and len(definition) > 10:
                        parsed_facts.append((term, definition, question_template.format(term)))
                        break
                        
        if len(parsed_facts) < num_questions:
            for sentence in sentences:
                if " is " in sentence:
                    parts = sentence.split(" is ")
                    term = parts[0].strip()
                    definition = "is " + " is ".join(parts[1:]).strip()
                    if 2 < len(term) < 40 and len(definition) > 15:
                        parsed_facts.append((term, definition, f"What is known about: {term}?"))

        # Deduplicate facts by term to avoid duplicate questions
        seen_terms = set()
        unique_facts = []
        for fact in parsed_facts:
            term_key = fact[0].strip().lower()
            if term_key not in seen_terms:
                seen_terms.add(term_key)
                unique_facts.append(fact)

        random.shuffle(unique_facts)
        selected_facts = unique_facts[:num_questions]
        
        if not selected_facts:
            return self._generate_generic_quiz("Uploaded Notes", num_questions)

        for idx, (term, definition, question_text) in enumerate(selected_facts):
            if idx % 2 == 0:
                # MCQ question type
                correct_ans = definition.strip()
                other_defs = [f[1].strip() for f in unique_facts if f[0].strip().lower() != term.lower()]
                
                seen_defs = set()
                deduped_other_defs = []
                for od in other_defs:
                    if od.lower() not in seen_defs and od.lower() != correct_ans.lower():
                        seen_defs.add(od.lower())
                        deduped_other_defs.append(od)
                
                generic_options = [
                    "A variable or function that is not initialized.",
                    "An outdated methodology replaced by modern frameworks.",
                    "An optimized algorithm for sorting large arrays.",
                    "A configuration file located in the root directory.",
                    "A standard mechanism for handling async operations.",
                    "An encapsulation wrapper for security credentials."
                ]
                for go in generic_options:
                    if len(deduped_other_defs) >= 3:
                        break
                    if go.lower() != correct_ans.lower() and go.lower() not in seen_defs:
                        seen_defs.add(go.lower())
                        deduped_other_defs.append(go)
                
                distractors = random.sample(deduped_other_defs, min(3, len(deduped_other_defs)))
                options = [correct_ans] + distractors
                random.shuffle(options)
                correct_idx = options.index(correct_ans)
                
                questions.append({
                    "type": "mcq",
                    "question": question_text,
                    "options": options,
                    "correct": str(correct_idx),
                    "explanation": f"Based on your notes: '{term} {definition}'."
                })
            else:
                # Short Answer question type
                questions.append({
                    "type": "short_answer",
                    "question": f"Based on your notes, what concept is described as: '{definition.strip()}'?",
                    "options": [],
                    "correct": term.strip(),
                    "explanation": f"Based on your notes: '{term}' refers to '{definition.strip()}'."
                })
            
        return questions

    def _generate_generic_quiz(self, topic: str, num_questions: int, skill_level: str = "Beginner") -> List[Dict[str, Any]]:
        """Fallback generator when no pre-built topic matches and no notes are provided."""
        topic_title = topic.capitalize() if topic else "General Studies"
        
        # Beginner questions
        beginner_q = [
            {
                "type": "mcq",
                "question": f"Which of the following is a primary best practice when studying {topic_title} at a Beginner level?",
                "options": [
                    "Memorizing text word-for-word without understanding.",
                    "Breaking down complex concepts into small, digestible parts and testing yourself.",
                    "Reading the same page repeatedly for hours without breaks.",
                    "Avoiding practice exercises until the final exam day."
                ],
                "correct": "1",
                "explanation": f"Active recall and spaced repetition are highly effective for learning the fundamentals of {topic_title}."
            },
            {
                "type": "short_answer",
                "question": "What is the name of the learning technique that involves teaching a concept in simple terms to find knowledge gaps?",
                "options": [],
                "correct": "Feynman Technique",
                "explanation": "The Feynman technique involves teaching a concept in simple terms to expose gaps in understanding."
            },
            {
                "type": "coding",
                "question": f"Write a simple Python print statement to output the message 'Welcome to {topic_title} study session!'",
                "options": [],
                "correct": f"print('Welcome to {topic_title} study session!')",
                "explanation": "In Python, the print() function is used to output text to the console."
            },
            {
                "type": "mcq",
                "question": "What is the benefit of taking short practice quizzes regularly?",
                "options": [
                    "It causes test anxiety and should be avoided",
                    "It triggers active retrieval, strengthening long-term memory pathways",
                    "It guarantees a perfect score on final evaluations",
                    "It replaces the need to review study material entirely"
                ],
                "correct": "1",
                "explanation": "Practice testing, or active retrieval, is proven to enhance memory retention and identify knowledge gaps."
            },
            {
                "type": "short_answer",
                "question": "In Python, what is the data type for storing true/false values?",
                "options": [],
                "correct": "bool",
                "explanation": "Booleans (bool) store binary values: True or False."
            }
        ]
        
        # Intermediate questions
        intermediate_q = [
            {
                "type": "mcq",
                "question": f"When learning {topic_title} at an Intermediate level, what is the best approach to practice?",
                "options": [
                    "Only reading code snippets written by others.",
                    "Building modular, mini-projects and implementing error handling.",
                    "Copying and pasting large files without code analysis.",
                    "Memorizing API docs instead of executing code."
                ],
                "correct": "1",
                "explanation": "Building small modular projects teaches you structure, logic flow, and debugging skills."
            },
            {
                "type": "short_answer",
                "question": "In Python, which list method is used to add an item to the end of a list?",
                "options": [],
                "correct": "append",
                "explanation": "The append() method adds a single element to the end of a list."
            },
            {
                "type": "coding",
                "question": "Write a Python function named `greet` that takes a parameter `name` and returns 'Hello ' + name.",
                "options": [],
                "correct": "def greet(name):\n    return 'Hello ' + name",
                "explanation": "Functions are defined using the 'def' keyword followed by argument parameters and a return statement."
            },
            {
                "type": "mcq",
                "question": f"Why is writing unit tests valuable when studying {topic_title} components?",
                "options": [
                    "It slows down learning and is only for commercial products.",
                    "It validates code logic, establishes specifications, and builds refactoring confidence.",
                    "It guarantees that the code runs faster in the compiler.",
                    "It replaces the need for code reviews entirely."
                ],
                "correct": "1",
                "explanation": "Unit testing forces you to design decoupled code and verifies that your functions behave as expected."
            },
            {
                "type": "short_answer",
                "question": "Which Python keyword is used to handle exceptions inside try blocks?",
                "options": [],
                "correct": "except",
                "explanation": "The except keyword catches and handles specific exceptions raised within the try block."
            }
        ]
        
        # Advanced questions
        advanced_q = [
            {
                "type": "mcq",
                "question": f"What is a critical consideration when designing advanced systems for {topic_title}?",
                "options": [
                    "Maximizing physical code files to show system scale.",
                    "Analyzing performance bottlenecks, architectural scalability, and security bounds.",
                    "Avoiding code documentation to protect intellectual property.",
                    "Using default settings for all external APIs and databases."
                ],
                "correct": "1",
                "explanation": "Advanced design requires balancing throughput, memory profiles, safety controls, and clean abstractions."
            },
            {
                "type": "short_answer",
                "question": "What is the term for a Python class that defines the behavior and creation rules of other classes?",
                "options": [],
                "correct": "metaclass",
                "explanation": "A metaclass is a class of a class, defining how classes are constructed."
            },
            {
                "type": "coding",
                "question": "Write a lambda function in Python that takes a number x and returns its square.",
                "options": [],
                "correct": "lambda x: x ** 2",
                "explanation": "A lambda function is an anonymous one-liner: lambda x: x ** 2."
            },
            {
                "type": "mcq",
                "question": "In advanced system designs, what does the term 'Loose Coupling' signify?",
                "options": [
                    "Modules having high knowledge of each other's internal variables.",
                    "Minimizing dependencies between components using abstractions or interfaces.",
                    "Connecting classes via static variables and global scopes.",
                    "Designing code without clear package structures."
                ],
                "correct": "1",
                "explanation": "Loose coupling reduces system rigidity, allowing components to be modified or replaced independently."
            }
        ]
        
        selected_q = beginner_q
        if skill_level == "Intermediate":
            selected_q = intermediate_q
        elif skill_level == "Advanced":
            selected_q = advanced_q
            
        shuffled = list(selected_q)
        random.shuffle(shuffled)
        return shuffled[:num_questions]

    def _execute_simulation(self, prompt: str, session_state: SessionState) -> str:
        topic = session_state.get("quiz_topic", "General Studies")
        num_q = session_state.get("quiz_count", 5)
        notes = session_state.get("notes_text", None)
        
        quiz = self.generate_quiz(topic, num_q, notes)
        
        chat_format = [f"### 📝 Practice Quiz: {topic.capitalize()}"]
        for idx, q in enumerate(quiz):
            chat_format.append(f"\n**Q{idx+1}: {q['question']}**")
            for o_idx, opt in enumerate(q['options']):
                chat_format.append(f"  {chr(65+o_idx)}) {opt}")
        
        return "\n".join(chat_format)
